/*Write a PL/SQL block to accept product name, qty and price from user and then calculate discount in Rs. based on the given (%). */

SET SERVEROUTPUT ON;

DECLARE 

V_PRODUCT VARCHAR2(50);
V_QUANTITY NUMBER;
v_PRICE NUMBER;
V_TOTAL NUMBER;
V_DISCOUNT NUMBER;
V_DISCOUNT_RS NUMBER;

BEGIN 

V_PRODUCT := '&PRODUCT';
V_QUANTITY := &QUANTITY;
V_PRICE := &PRICE;
V_TOTAL := V_PRICE * V_QUANTITY;
V_DISCOUNT := &DISCOUNT;
V_DISCOUNT_RS := (V_DISCOUNT * V_TOTAL)/100;

DBMS_OUTPUT.PUT_LINE('PRICE OF YOUR ITEM IS AFTER THE DISCOUNT = RS ' || V_DISCOUNT_RS);


END;
/