/* Write a PL/SQL block to calculate the square and cube of the given number.*/

SET SERVEROUTPUT ON;

DECLARE 

V_GIVEN_NUM NUMBER;
V_SQUARE NUMBER;
V_CUBE NUMBER;

BEGIN

V_GIVEN_NUM := 5;
V_SQUARE := V_GIVEN_NUM * V_GIVEN_NUM;
V_CUBE := V_GIVEN_NUM * V_GIVEN_NUM * V_GIVEN_NUM;

DBMS_OUTPUT.PUT_LINE('SQUARE OF THE NUMBER IS: ' || V_SQUARE);
DBMS_OUTPUT.PUT_LINE('CUBE OF THE GIVEN NUMBER IS:' || V_CUBE);

END;
/